"""userimage update1

Revision ID: 00b16485489e
Revises: 234466f0698d
Create Date: 2022-03-28 23:14:42.269590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b16485489e'
down_revision = '234466f0698d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userimage', sa.Column('Id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userimage', 'Id')
    # ### end Alembic commands ###
