"""add image

Revision ID: 07e6c65e2ce4
Revises: 41593c71960c
Create Date: 2022-03-28 19:31:39.786188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e6c65e2ce4'
down_revision = '41593c71960c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('image_name', sa.String(), nullable=True))
    op.add_column('userdata', sa.Column('image_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'image_type')
    op.drop_column('userdata', 'image_name')
    # ### end Alembic commands ###
