"""set pk userimg

Revision ID: 1614316b8e85
Revises: 00b16485489e
Create Date: 2022-03-28 23:21:23.931361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1614316b8e85'
down_revision = '00b16485489e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
