"""set userimage rel

Revision ID: 234466f0698d
Revises: 5901d8c97395
Create Date: 2022-03-28 23:06:52.629990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234466f0698d'
down_revision = '5901d8c97395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
