"""add dateinfo in userdata

Revision ID: 3fe864ffdde8
Revises: 07e6c65e2ce4
Create Date: 2022-03-28 22:09:45.794170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fe864ffdde8'
down_revision = '07e6c65e2ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('DOB', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('userdata', sa.Column('M_passing_year', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('userdata', sa.Column('Fsc_passing_year', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('userdata', 'image_name')
    op.drop_column('userdata', 'image_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('image_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('userdata', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('userdata', 'Fsc_passing_year')
    op.drop_column('userdata', 'M_passing_year')
    op.drop_column('userdata', 'DOB')
    # ### end Alembic commands ###
