"""adding images col

Revision ID: 41593c71960c
Revises: cb9492bc489d
Create Date: 2022-03-27 14:42:59.729652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41593c71960c'
down_revision = 'cb9492bc489d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userimage',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['userdata.Id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userimage')
    # ### end Alembic commands ###
