"""set date

Revision ID: 5901d8c97395
Revises: b841f160bebc
Create Date: 2022-03-28 22:28:52.274719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5901d8c97395'
down_revision = 'b841f160bebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
