"""create userdata  table

Revision ID: a13802ab87cc
Revises: 
Create Date: 2022-03-18 20:44:26.581529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13802ab87cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdata',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('First_Name', sa.String(), nullable=False),
    sa.Column('Last_Name', sa.String(), nullable=False),
    sa.Column('Father_Name', sa.String(), nullable=False),
    sa.Column('Matric_Marks', sa.Integer(), nullable=False),
    sa.Column('Out_of_Matric_Marks', sa.Integer(), nullable=False),
    sa.Column('FSC_Marks', sa.Integer(), nullable=False),
    sa.Column('Out_Of_FSC_Marks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_userdata_Id'), 'userdata', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userdata_Id'), table_name='userdata')
    op.drop_table('userdata')
    # ### end Alembic commands ###
