"""relation bw tables

Revision ID: cb9492bc489d
Revises: f6cd5afe4665
Create Date: 2022-03-23 23:45:28.386697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9492bc489d'
down_revision = 'f6cd5afe4665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
