"""add onwerid in userdata

Revision ID: f6cd5afe4665
Revises: 8fd75fa9be73
Create Date: 2022-03-23 16:24:25.197496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cd5afe4665'
down_revision = '8fd75fa9be73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userdata', 'user', ['owner_id'], ['Id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userdata', type_='foreignkey')
    op.drop_column('userdata', 'owner_id')
    # ### end Alembic commands ###
